### Get One Trainer

GET http://localhost:9080/gym-app/api/trainers/00000000-0000-0000-0000-000000000001

### Get One Trainer (Doesn't exist)

GET http://localhost:9080/gym-app/api/trainers/00000000-0000-0000-0000-000000000005

### Get All Trainers

GET http://localhost:9080/gym-app/api/trainers

### Get Trainer Avatar

GET http://localhost:9080/gym-app/api/trainers/00000000-0000-0000-0000-000000000001/avatar

### Create Trainer Avatar.

PUT http://localhost:9080/gym-app/api/trainers/00000000-0000-0000-0000-000000000002/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="avatar.png'

< src/main/resources/avatar/avatar.png
--boundary--

### Patch Trainer Avatar.

PATCH http://localhost:9080/gym-app/api/trainers/00000000-0000-0000-0000-000000000002/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="avatar.png'

< src/main/resources/avatar/avatar.png
--boundary--

### Delete Trainer Avatar

DELETE http://localhost:9080/gym-app/api/trainers/00000000-0000-0000-0000-000000000002/avatar



