### Get One Trainer

GET http://localhost:9080/gym-app/api/trainers/00000000-0000-0000-0000-000000000001

### Get One Trainer (Doesn't exist)

GET http://localhost:9080/gym-app/api/trainers/00000000-0000-0000-0000-000000000005

### Get All Trainers

GET http://localhost:9080/gym-app/api/trainers

### Get Trainer Avatar

GET http://localhost:9080/gym-app/api/trainers/00000000-0000-0000-0000-000000000001/avatar

#### Create Trainer

PUT http://localhost:9080/gym-app/api/trainers/00000000-0000-0000-0001-000000000005
Content-Type: application/json

{
  "name": "Trener",
  "yearsOfTraining": 3,
  "birthDate": "1990-05-21"
}

### Create Trainer Avatar.

PUT http://localhost:9080/gym-app/api/trainers/00000000-0000-0000-0000-000000000001/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="avatar.png'

< src/main/resources/avatar/avatar.png
--boundary--

### Patch Trainer Avatar

PATCH http://localhost:9080/gym-app/api/trainers/00000000-0000-0000-0000-000000000001/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="avatar2.png'

< src/main/resources/avatar/avatar2.png
--boundary--

### Delete Trainer Avatar

DELETE http://localhost:9080/gym-app/api/trainers/00000000-0000-0000-0000-000000000001/avatar

### Get One Member

GET http://localhost:9080/gym-app/api/members/00000000-0000-0000-0002-000000000001

### Get One Member (Doesn't exist)

GET http://localhost:9080/gym-app/api/members/00000000-0000-0000-0002-000000000007

### Get All Members

GET http://localhost:9080/gym-app/api/members

#### Create Member

PUT http://localhost:9080/gym-app/api/members/00000000-0000-0000-0002-000000000005
Content-Type: application/json

{
  "name": "Pawel",
  "benchPressMax": "40",
  "trainer": "00000000-0000-0000-0000-000000000001",
  "gym": "00000000-0000-0000-0001-000000000001"
}

### Update Member

PATCH http://localhost:9080/gym-app/api/members/00000000-0000-0000-0002-000000000001
Content-Type: application/json

{
  "name": "Oskar",
  "benchPressMax": "120"
}


### Delete Member

DELETE http://localhost:9080/gym-app/api/members/00000000-0000-0000-0002-000000000005

### Get Trainer Members

GET http://localhost:9080/gym-app/api/trainers/00000000-0000-0000-0000-000000000001/members

### Get One Gym

GET http://localhost:9080/gym-app/api/gyms/00000000-0000-0000-0001-000000000002

### Get One Gym (Doesn't exist)

GET http://localhost:9080/gym-app/api/gyms/00000000-0000-0000-0001-000000000005

### Get All Gyms

GET http://localhost:9080/gym-app/api/gyms

### Create Gym

PUT http://localhost:9080/gym-app/api/gyms/00000000-0000-0000-0001-000000000004
Content-Type: application/json

{
  "name": "Nowa",
  "numberOfEquipment": 32,
  "gymType":"NORMAL"
}

### Get Gym Members

GET http://localhost:9080/gym-app/api/gyms/00000000-0000-0000-0001-000000000001/members

### Update Gym

PATCH http://localhost:9080/gym-app/api/gyms/00000000-0000-0000-0001-000000000001
Content-Type: application/json

{
  "name": "Nowa2",
  "numberOfEquipment": 32,
  "gymType":"NORMAL"
}